version: '2.1'
orbs:
  android: circleci/android@2.3.0
parameters:
  system_image:
    type: string
    default: "system-images;android-33;google_apis;x86_64"
  machine_image:
    type: string
    default: "2023.10.1"
jobs:
  test:
    executor:
      name: android/android-machine
      tag: << parameters.machine_image >>
    parameters:
      system_image:
        type: string
    steps:
      - checkout
      - run: ruby -v
      - run: sdkmanager --list
      - android/start-emulator-and-run-tests:
          system-image: << parameters.system_image >>
workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              system_image: ["system-images;android-33;google_apis;x86_64", "system-images;android-30;google_apis;x86_64"]
              machine_image: ["2023.10.1", "2023.09.1", "2023.08.1", "2023.07.1", "2023.06.1", "2023.05.1", "2023.04.1", "2023.03.1"]
