version: '2.1'
orbs:
  android: circleci/android@2.3.0
jobs:
  test:
    executor:
      name: android/android-machine
      tag: '2023.11.1'
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          system-image: system-images;android-33;google_apis;x86_64
workflows:
  test:
    jobs:
      - test
